scss_files: 'app/**/*.scss'

exclude: 'app/assets/stylesheets/style/fonts.css'

linters:
  Comment:
    exclude:
      - 'app/assets/stylesheets/application.css.scss'
      - 'app/assets/stylesheets/curate.css.scss'
  ImportantRule:
    exclude: 'app/assets/stylesheets/modules/accessibility.css.scss'
  NameFormat:
    exclude:
      - 'app/assets/stylesheets/global-variables.scss'
      - 'app/assets/stylesheets/layout/positioning.css.scss'
  QualifyingElement:
    exclude: 'app/assets/stylesheets/style/nd-theme-print.css.scss'
  SelectorFormat:
    exclude:
      - 'app/assets/stylesheets/layout/positioning.css.scss'
      - 'app/assets/stylesheets/modules/multi_value_fields.css.scss'
  VendorPrefix:
    exclude: 'app/assets/stylesheets/modules/concerns.css.scss'
