language: ruby
rvm:
  - "2.2.10"
  - "2.3.8"

matrix:
  allow_failures:
    - rvm: "2.3.8"

script: 'bundle exec rake curatend:ci_prep RAILS_ENV=ci && bundle exec rake spec curatend:lint_erb SPEC_OPTS="--tag ~js:true" RAILS_ENV=ci'

services:
  - docker

notifications:
  irc: "irc.freenode.org#ndlib"

bundler_args: --without headless debug

before_install:
  - sudo service mysql stop
  - docker-compose -f docker-compose-test.yml up -d
  - gem install bundler -v 1.16.6
