architecture:
  key: "architecture"
  identifier: "Architecture"
  selectable: true
business:
  key: "business"
  identifier: "Business"
  selectable: false
accounting:
  key: "accounting"
  identifier: "Business::Accounting"
  selectable: true
finance:
  key: "finance"
  identifier: "Business::Finance"
  selectable: true
information_technology_management:
  key: "information_technology_management"
  identifier: "Business::Information Technology Management"
  selectable: true
management:
  key: "management"
  identifier: "Business::Management"
  selectable: true
marketing:
  key: "marketing"
  identifier: "Business::Marketing"
  selectable: true
engineering:
  key: "engineering"
  identifier: "Engineering"
  selectable: false
aerospace_engineering:
  key: "aerospace_engineering"
  identifier: "Engineering::Aerospace Engineering"
  selectable: true
chemical_and_biomolecular_engineering:
  key: "chemical_and_biomolecular_engineering"
  identifier: "Engineering::Chemical and Biomolecular Engineering"
  selectable: true
civil_engineering:
  key: "civil_engineering"
  identifier: "Engineering::Civil Engineering"
  selectable: true
computer_engineering:
  key: "computer_engineering"
  identifier: "Engineering::Computer Engineering"
  selectable: true
electrical_engineering:
  key: "electrical_engineering"
  identifier: "Engineering::Electrical Engineering"
  selectable: true
engineering_general:
  key: "engineering_general"
  identifier: "Engineering::Engineering(General)"
  selectable: true
environmental_engineering:
  key: "environmental_engineering"
  identifier: "Engineering::Environmental Engineering"
  selectable: true
mechanical_engineering:
  key: "mechanical_engineering"
  identifier: "Engineering::Mechanical Engineering"
  selectable: true
nanotechnology:
  key: "nanotechnology"
  identifier: "Engineering::Nanotechnology"
  selectable: true
humanities:
  key: "humanities"
  identifier: "Humanities"
  selectable: false
africana_studies:
  key: "africana_studies"
  identifier: "Humanities::Africana Studies"
  selectable: true
american_studies:
  key: "american_studies"
  identifier: "Humanities::American Studies"
  selectable: true
arab_studies:
  key: "arab_studies"
  identifier: "Humanities::Arab Studies"
  selectable: true
art_art_history_and_design:
  key: "art_art_history_and_design"
  identifier: "Humanities::Art, Art History and Design"
  selectable: true
asian_languages_and_literature:
  key: "asian_languages_and_literature"
  identifier: "Humanities::Asian Languages and Literature"
  selectable: false
chinese_languages_and_literature:
  key: "chinese_languages_and_literature"
  identifier: "Humanities::Asian Languages and Literature::Chinese Languages and Literature"
  selectable: true
japanese_languages_and_literature:
  key: "japanese_languages_and_literature"
  identifier: "Humanities::Asian Languages and Literature::Japanese Languages and Literature"
  selectable: true
asian_studies:
  key: "asian_studies"
  identifier: "Humanities::Asian Studies"
  selectable: false
chinese_studies:
  key: "chinese_studies"
  identifier: "Humanities::Asian Studies::Chinese Studies"
  selectable: true
japanese_studies:
  key: "japanese_studies"
  identifier: "Humanities::Asian Studies::Japanese Studies"
  selectable: true
korean_studies:
  key: "korean_studies"
  identifier: "Humanities::Asian Studies::Korean Studies"
  selectable: true
catholic_studies:
  key: "catholic_studies"
  identifier: "Humanities::Catholic Studies"
  selectable: true
classics:
  key: "classics"
  identifier: "Humanities::Classics"
  selectable: false
education:
  key: "education"
  identifier: "Humanities::Classics::Education"
  selectable: true
english_language_and_literature:
  key: "english_language_and_literature"
  identifier: "Humanities::Classics::English Language and Literature"
  selectable: true
film_television_and_theatre:
  key: "film_television_and_theatre"
  identifier: "Humanities::Film, Television and Theatre"
  selectable: true
gender_studies:
  key: "gender_studies"
  identifier: "Humanities::Gender Studies"
  selectable: true
german_language_and_literature:
  key: "german_language_and_literature"
  identifier: "Humanities::German Language and Literature"
  selectable: true
history:
  key: "history"
  identifier: "Humanities::History"
  selectable: false
us_and_canada:
  key: "us_and_canada"
  identifier: "Humanities::History::U.S. and Canada"
  selectable: true
western_european_and_world:
  key: "western_european_and_world"
  identifier: "Humanities::History::Western European and World"
  selectable: true
irish_language_and_literature:
  key: "irish_language_and_literature"
  identifier: "Humanities::Irish Language and Literature"
  selectable: true
irish_studies:
  key: "irish_studies"
  identifier: "Humanities::Irish Studies"
  selectable: true
journalism:
  key: "journalism"
  identifier: "Humanities::Journalism"
  selectable: true
latin_american_studies:
  key: "latin_american_studies"
  identifier: "Humanities::Latin American Studies"
  selectable: true
latino_studies:
  key: "latino_studies"
  identifier: "Humanities::Latino Studies"
  selectable: true
library_and_information_science:
  key: "library_and_information_science"
  identifier: "Humanities::Library and Information Science"
  selectable: true
linguistics:
  key: "linguistics"
  identifier: "Humanities::linguistics"
  selectable: true
medieval_studies:
  key: "medieval_studies"
  identifier: "Humanities::Medieval Studies"
  selectable: true
music:
  key: "music"
  identifier: "Humanities::Music"
  selectable: true
philosophy:
  key: "philosophy"
  identifier: "Humanities::Philosophy"
  selectable: true
romance_languages_and_literature:
  key: "romance_languages_and_literature"
  identifier: "Humanities::Romance Languages and Literature"
  selectable: false
french_language_and_literature:
  key: "french_language_and_literature"
  identifier: "Humanities::Romance Languages and Literature::French Language and Literature"
  selectable: true
italian_language_and_literature:
  key: "italian_language_and_literature"
  identifier: "Humanities::Romance Languages and Literature::Italian Language and Literature"
  selectable: true
portuguese_language_and_literature:
  key: "portuguese_language_and_literature"
  identifier: "Humanities::Romance Languages and Literature::Portuguese Language and Literature"
  selectable: true
spanish_language_and_literature:
  key: "spanish_language_and_literature"
  identifier: "Humanities::Romance Languages and Literature::Spanish Language and Literature"
  selectable: true
russian_and_east_european_studies:
  key: "russian_and_east_european_studies"
  identifier: "Humanities::Russian and East European Studies"
  selectable: true
russian_language_and_literature:
  key: "russian_language_and_literature"
  identifier: "Humanities::Russian Language and Literature"
  selectable: true
sports_studies:
  key: "sports_studies"
  identifier: "Humanities::Sports Studies"
  selectable: true
theology_and_religion:
  key: "theology_and_religion"
  identifier: "Humanities::Theology and Religion"
  selectable: true
science:
  key: "science"
  identifier: "Science"
  selectable: false
astronomy:
  key: "astronomy"
  identifier: "Science::Astronomy"
  selectable: true
biology:
  key: "biology"
  identifier: "Science::Biology"
  selectable: false
biology_and_life_sciences:
  key: "biology_and_life_sciences"
  identifier: "Science::Biology::Biology and Life Sciences"
  selectable: true
biomedical_engineering:
  key: "biomedical_engineering"
  identifier: "Science::Biology::Biomedical Engineering"
  selectable: true
medicine_and_health:
  key: "medicine_and_health"
  identifier: "Science::Biology::Medicine and Health"
  selectable: true
chemistry_and_biochemistry:
  key: "chemistry_and_biochemistry"
  identifier: "Science::Chemistry and Biochemistry"
  selectable: true
geology:
  key: "geology"
  identifier: "Science::Geology"
  selectable: true
physics:
  key: "physics"
  identifier: "Science::Physics"
  selectable: true
chemistry_and_biochemistry:
  key: "history_and_philosophy_of_science"
  identifier: "Science::History and Philosophy of Science"
  selectable: true
materials_science_including_biomaterials:
  key: "materials_science_including_biomaterials"
  identifier: "Science::Materials Science (including Biomaterials)"
  selectable: true
mathematics:
  key: "mathematics"
  identifier: "Science::Mathematics"
  selectable: true
mathematics_and_statistics:
  key: "applied_mathematics_and_statistics"
  identifier: "Science::Applied and Computational Mathematics and Statistics"
  selectable: true
social_science:
  key: "social_science"
  identifier: "Social Science"
  selectable: false
anthropology:
  key: "anthropology"
  identifier: "Social Science::Anthropology"
  selectable: true
economics:
  key: "economics"
  identifier: "Social Science::Economics"
  selectable: true
peace_studies:
  key: "peace_studies"
  identifier: "Social Science::Peace Studies"
  selectable: true
political_science:
  key: "political_science"
  identifier: "Social Science::Political Science"
  selectable: true
psychology:
  key: "psychology"
  identifier: "Social Science::Psychology"
  selectable: true
sociology:
  key: "sociology"
  identifier: "Social Science::Sociology"
  selectable: true
