development:
  etd_manager_usernames:
  - etd_manager@example.com
ci:
  etd_manager_usernames:
  - etd_manager@example.com
test:
  etd_manager_usernames:
  - etd_manager@example.com
production:
  etd_manager_usernames:
  - etd_manager@example.com
