#
# FYI: This file is replaced by a copy for deploys
# to ci, pre_production, and production.
#

# omit development section to use default minter
#
#development:
#  server: localhost:13001
#  pool:   curate-nd

# omit test section to use default minter

