"zzz_characterize,characterize": 1
"audio,audit,characterize,collection_adder,doi_miniting_requests,event,help_request_notifications,permissions,resolrize,sufia,unzip,video": 1
"resolrize,permissions": 2
"*": 2
