name: Ruby CI

on: 
  push:
    branches: all
  pull_request: 
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: [2.6.x, 2.5.x, 2.4.x]
      fail-fast: true

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Build and test with Rake
      run: |
        sudo apt-get update
        sudo apt-get install -y libmysqlclient-dev
        gem install bundler:1.17.3
        bundle install --jobs 4 --retry 3
        bundle exec rake curatend:ci_prep RAILS_ENV=ci && bundle exec rake spec curatend:lint_erb SPEC_OPTS="--tag ~js:true" RAILS_ENV=ci
